import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';

import Header from '../components/Header';
import CartProvider from '../contexts/cart';
import { ToastContainer } from 'react-toastify';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="px-[2em] py-[2em]">
          <CartProvider>
            <Header />
            <section className="mt-[1em]">
              {children}
            </section>
            <ToastContainer />
          </CartProvider>
        </div>
      </body>
    </html>
  );
}
